import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisProvider from "../(my-app)/components/LenisProvider";
import NavWrapper from "../(my-app)/components/NavWrapper";
import Footer from "../(my-app)/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <LenisProvider>
          <NavWrapper />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
